- name: Install python in target node with ansible
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: "cat < {{ role_path }}/scripts/script.sh"
    args:
      executable: /bin/bash
